# ------------------------------------------------
# Camerons Ansible PlayBook 
#
# Adding an existing inventory to a play book .
# ------------------------------------------------
- name: Add inventory to a group
  hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    external_ip: '172.16.25.23'

  tasks:
  - name: add host to existing group
    add_host:     
      name: 172.16.25.23
      groups: windows_group
    